const $=i=>document.getElementById(i),S=[...document.querySelectorAll('main>section')];let cur=0,man=false;
const go=i=>S[Math.max(0,Math.min(S.length-1,i))].scrollIntoView({behavior:'smooth'});
const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)cur=S.indexOf(e.target)}),{rootMargin:'-45% 0px -45% 0px'});S.forEach(s=>io.observe(s));
const rv=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('v');if(e.target.id=='gw')gauges()}}),{threshold:.15});document.querySelectorAll('.r').forEach(e=>rv.observe(e));
addEventListener('scroll',()=>{const p=Math.round(scrollY/(document.body.scrollHeight-innerHeight)*100)||0;$('bar').style.width=p+'%';const r=$('s4').getBoundingClientRect(),q=(innerHeight-r.top)/(innerHeight+r.height);if(!man&&q>.2&&q<.8)st(Math.min(4,Math.max(0,Math.floor((q-.2)/.6*5))))},{passive:true});
addEventListener('keydown',e=>{if(/INPUT|SELECT|TEXTAREA/.test(document.activeElement.tagName))return;const k=e.key;if(['ArrowDown','PageDown','ArrowRight'].includes(k)){e.preventDefault();go(cur+1)}else if(['ArrowUp','PageUp','ArrowLeft'].includes(k)){e.preventDefault();go(cur-1)}});
// hero bad button
$('bad').onclick=function(){const t=$('bw');t.style.display='block';t.textContent='Kamu baru merasakan UX buruk: target kecil, kontras rendah, label ambigu. Ini versi yang baik.';this.className='b';this.style.cssText='';this.textContent='Mulai presentasi ↓';this.onclick=()=>go(1);setTimeout(()=>t.style.display='none',5000)};
// team
[['Eiffel Nailah Suanto','2517020052','eiffel','50% 18%'],['Dina Kurnia','2517020035','dina','50% 77%'],['Aisyah Okta Ramadhani','2517020040','aisyah','50% 59%']].forEach((m,i)=>{$('bw2').insertAdjacentHTML('beforeend','<div class="bd"><div style="width:44px;height:8px;border-radius:9px;background:var(--bg);margin:0 auto 12px"></div><div class="ph"><img src="images/'+m[2]+'.jpg" alt="Foto '+m[0]+'" style="object-position:'+m[3]+'"></div><div class="m" style="color:var(--mint);margin-top:12px">ANGGOTA 0'+(i+1)+'</div><div class="nm">'+m[0]+'</div><div class="m" style="color:var(--dim);margin-top:4px">NIM '+m[1]+'</div><div class="bc"></div></div>')});
// venn
const VD={e:['Effectiveness','Ketepatan dan kelengkapan pengguna dalam mencapai tujuannya. Contoh: pesanan berhasil dibuat sampai selesai.'],f:['Efficiency','Sumber daya (waktu, tenaga, jumlah langkah) yang dipakai dibandingkan hasil yang dicapai. Contoh: memesan hanya dengan beberapa ketukan.'],s:['Satisfaction','Sejauh mana respons fisik, kognitif, dan emosional pengguna sesuai dengan kebutuhan dan harapannya. Contoh: tidak bingung dan tidak kesal saat memakai.']};
document.querySelectorAll('.vc').forEach(g=>{const f=()=>{document.querySelectorAll('.vc').forEach(x=>x.classList.toggle('on',x==g));$('vh').textContent=VD[g.dataset.k][0];$('vt').textContent=VD[g.dataset.k][1]};g.onclick=f;g.onkeydown=e=>{if(e.key=='Enter')f()}});
// importance
[['Pengguna sering salah dan frustrasi','Less errors','Mengurangi kesalahan dan frustrasi pengguna.'],['Tugas selesai lama dan berbelit','Save time','Menghemat waktu, karena tugas lebih cepat selesai.'],['Pengguna pindah ke pesaing','Konversi dan loyalitas naik','Pengguna yang kesulitan biasanya langsung pindah ke pesaing.'],['Perbaikan mahal setelah rilis','Lower cost','Memperbaiki masalah desain di awal lebih murah daripada setelah produk rilis, dan beban layanan pelanggan berkurang.']].forEach((w,i)=>$('wl').insertAdjacentHTML('beforeend','<div class="wr"><span class="m" style="color:var(--dim);padding-top:6px">0'+(i+1)+'</span><div><span class="old">'+w[0]+'</span> <span style="color:var(--pk)">→</span><div class="new">'+w[1]+'</div><p style="margin:4px 0 0;font-size:15px">'+w[2]+'</p></div></div>'));
// radar
const C=[['Learnability','Seberapa mudah pengguna baru memakainya.'],['Efficiency','Seberapa cepat pengguna yang sudah mahir menyelesaikan tugas.'],['Memorability','Seberapa mudah diingat kembali setelah lama tidak dipakai.'],['Errors','Jumlah dan tingkat keparahan kesalahan serta kemudahan pemulihannya.'],['Satisfaction','Seberapa menyenangkan pemakaiannya.']],V=[85,70,75,55,80];let ci=0;
function rd(){const cx=230,cy=200,R=140,P=(i,r)=>{const a=(-90+72*i)*Math.PI/180;return[cx+r*Math.cos(a),cy+r*Math.sin(a)]},pl=r=>[0,1,2,3,4].map(i=>P(i,r).join(',')).join(' ');let h=[.33,.66,1].map(k=>'<polygon points="'+pl(R*k)+'" fill="none" stroke="var(--line)"/>').join('');h+=[0,1,2,3,4].map(i=>'<line x1="'+cx+'" y1="'+cy+'" x2="'+P(i,R)[0]+'" y2="'+P(i,R)[1]+'" stroke="var(--line)"/>').join('');h+='<polygon points="'+V.map((v,i)=>P(i,R*v/100).join(',')).join(' ')+'" fill="rgba(255,95,162,.28)" stroke="var(--pk)" stroke-width="2"/>';h+=V.map((v,i)=>{const[x,y]=P(i,R*v/100),[lx,ly]=P(i,R+24);return'<circle cx="'+x+'" cy="'+y+'" r="'+(i==ci?12:8)+'" fill="'+(i==ci?'var(--pk)':'var(--bg)')+'" stroke="var(--pk)" stroke-width="3" pointer-events="none"/><circle cx="'+x+'" cy="'+y+'" r="24" fill="transparent" tabindex="0" role="button" aria-label="'+C[i][0]+'" style="cursor:pointer" onclick="ci='+i+';rd()" onkeydown="if(event.key==\'Enter\'){ci='+i+';rd();$(\'rs\').querySelectorAll(\'[role=button]\')['+i+'].focus()}"/><text x="'+lx+'" y="'+(ly+4)+'" text-anchor="middle" font-family="DM Mono" font-size="13" fill="var(--ink)">'+C[i][0].toUpperCase()+'</text>'}).join('');$('rs').innerHTML=h;$('rn').textContent=C[ci][0];$('rd').textContent=C[ci][1];$('rv').value=V[ci];$('rl').textContent=V[ci]}
$('rv').oninput=function(){V[ci]=+this.value;rd()};rd();
// A/B
document.querySelectorAll('.mk').forEach(b=>b.onclick=()=>{document.querySelectorAll('.mk').forEach(x=>x.classList.remove('on'));b.classList.add('on');$('ar').textContent='Kamu memilih Option '+b.dataset.c+'. Pilihan dipengaruhi kejelasan, hierarchy, dan usaha yang dibutuhkan pengguna. Kamu baru saja merasakan usability.'});
// steps
const ST=[['Menentukan tujuan','Menentukan apa yang ingin dicapai pengguna.'],['Mengenali pengguna','Mengetahui kebutuhan dan karakteristik pengguna.'],['Membuat desain','Merancang tampilan dan fungsi sistem agar mudah digunakan.'],['Melakukan pengujian','Meminta pengguna mencoba sistem.'],['Evaluasi dan perbaikan','Menemukan masalah lalu memperbaikinya.']];
ST.forEach((s,i)=>{const b=document.createElement('button');b.innerHTML='<i></i><span>'+(i+1)+'. '+s[0]+'</span>';b.onclick=()=>{man=true;st(i)};$('sn').appendChild(b)});
function st(i){[...$('sn').children].forEach((b,j)=>{b.classList.toggle('on',j==i);b.classList.toggle('pa',j<i)});$('tf').style.width=(i/4*80)+'%';$('tn').style.left=(10+i/4*80)+'%';$('sd').textContent=ST[i][0]+': '+ST[i][1]}st(0);
// gauges
const GL=[['EFEKTIVITAS','Berhasilkah menyelesaikan tugas?'],['EFISIENSI','Secepat apa tugas selesai?'],['KEPUASAN','Seberapa puas pengguna?'],['ERROR','Seberapa sering salah?']];
GL.forEach((g,i)=>$('gg').insertAdjacentHTML('beforeend','<div><svg viewBox="0 0 130 130" role="img" aria-label="'+g[0]+'"><circle cx="65" cy="65" r="54" fill="none" stroke="var(--line)" stroke-width="10"/><circle id="g'+i+'" cx="65" cy="65" r="54" fill="none" stroke="'+(i==3?'var(--pk)':'var(--mint)')+'" stroke-width="10" stroke-linecap="round" stroke-dasharray="339.3" stroke-dashoffset="339.3" transform="rotate(-90 65 65)"/><text id="t'+i+'" x="65" y="72" text-anchor="middle" font-family="Fraunces" font-weight="800" font-size="26" fill="var(--ink)">0%</text></svg><b class="m">'+g[0]+'</b><p style="font-size:14px">'+g[1]+'</p></div>'));
function gg(i,p){$('g'+i).style.strokeDashoffset=339.3*(1-p/100);$('t'+i).textContent=Math.round(p)+'%'}
function ef(){const t=Math.max(1,+$('nt').value),d=Math.min(t,Math.max(0,+$('ni').value));gg(0,d/t*100)}
function gauges(){ef();gg(1,76);gg(2,82);gg(3,26)}$('ni').oninput=$('nt').oninput=ef;
// cycle
const CY=[['Analisis kebutuhan','Mengenali pengguna, tujuan, dan konteks penggunaan.'],['Perancangan','Merancang tampilan dan alur agar mudah digunakan.'],['Pembuatan','Membangun prototipe atau sistem dari rancangan.'],['Pengujian','Pengguna mencoba menyelesaikan tugas.'],['Evaluasi','Menganalisis masalah yang ditemukan.'],['Perbaikan','Memperbaiki desain berdasarkan temuan.'],['Pengujian kembali','Menguji ulang agar masalah benar-benar teratasi. Lalu siklus berulang.']];let oi=0;
CY.forEach((c,i)=>{const a=(-90+360/7*i)*Math.PI/180,b=document.createElement('button');b.style.left=50+43*Math.cos(a)+'%';b.style.top=50+43*Math.sin(a)+'%';b.innerHTML='0'+(i+1)+'<br>'+c[0].toUpperCase();b.onclick=()=>os(i);$('or').appendChild(b)});
function os(i){oi=i;[...$('or').querySelectorAll('button')].forEach((b,j)=>b.classList.toggle('on',j==i));$('oc').innerHTML='<b>'+CY[i][0]+'</b>'+CY[i][1]}os(0);

// metode pengukuran
const MT=[['Kualitatif','Menjawab "mengapa": menggali alasan, perilaku, dan persepsi pengguna.',[['Thinking Aloud Protocol','Pengguna mengerjakan tugas sambil mengucapkan isi pikirannya secara lantang. Peneliti mencatat kebingungan dan harapannya, sehingga penyebab masalah terlihat.'],['Moderated Usability Testing','Pengujian yang didampingi moderator (tatap muka atau jarak jauh). Moderator memberi tugas, mengamati, dan boleh bertanya lanjutan langsung.'],['Field Observation','Mengamati pengguna memakai sistem di lingkungan aslinya, misalnya di rumah, kantor, atau jalan, untuk memahami konteks, gangguan, dan kebiasaan nyata.']]],
['Kuantitatif','Menjawab "seberapa baik": angka yang bisa dibandingkan antar-versi atau antar-sistem.',[['Task Completion Rate','Persentase tugas yang berhasil diselesaikan pengguna: (tugas berhasil ÷ total tugas) × 100%. Mengukur efektivitas.'],['System Usability Scale (SUS)','Kuesioner 10 pernyataan berskala 1 sampai 5 yang diubah menjadi skor 0 sampai 100. Skor rata-rata sekitar 68 sering dipakai sebagai acuan.'],['Single Ease Question (SEQ)','Satu pertanyaan setelah tiap tugas: "Seberapa mudah tugas ini?" dijawab pada skala 1 sampai 7. Singkat, dan bisa dipakai untuk setiap tugas.']]],
['Inspeksi','Penilaian oleh ahli, tanpa harus melibatkan banyak pengguna.',[['Heuristic Evaluation','Ahli menilai antarmuka dengan prinsip heuristik, misalnya 10 heuristik Nielsen, lalu mencatat pelanggaran beserta tingkat keparahannya.'],['Cognitive Walkthrough','Ahli menelusuri tiap langkah tugas dari sudut pandang pengguna baru: apakah ia tahu harus apa, melihat kontrolnya, dan paham hasilnya? Fokus pada learnability.'],['Pluralistic Walkthrough','Sesi telusur bersama oleh pengguna, pengembang, dan pakar usability yang membahas setiap langkah antarmuka secara berurutan.']]]];
MT.forEach((m,i)=>{const b=document.createElement('button');b.setAttribute('role','tab');b.textContent=m[0];b.onclick=()=>mt(i);$('mtab').appendChild(b)});
function mt(k){[...$('mtab').children].forEach((b,i)=>b.setAttribute('aria-selected',i==k));const m=MT[k];$('ml').innerHTML='<p style="font-size:19px;color:var(--ink)">'+m[1]+'</p>'+m[2].map((x,i)=>'<div class="wr"><span class="m" style="color:var(--dim);padding-top:6px">0'+(i+1)+'</span><div><b style="font:800 clamp(20px,2.6vw,28px)/1.2 Fraunces,serif">'+x[0]+'</b><p style="margin:4px 0 0;font-size:16px">'+x[1]+'</p></div></div>').join('')}mt(0);

// contoh kasus
const CT=[['Sebelum','<div class="cs2"><figure style="margin:0"><img class="cimg" src="images/ferplast-sebelum.jpg" alt="Halaman produk Ferplast sebelum perbaikan: dua tombol beli besar, kode SKU, dan tanpa informasi pengembalian"></figure><div><b style="font:800 28px Fraunces,serif">Temuan pengujian</b><ol><li><span><b>Dua tombol beli membingungkan.</b> Satu menambah ke keranjang, satu lagi langsung ke Shop Pay yang meminta verifikasi nomor ponsel. Kalau salah klik, tidak ada jalan kembali yang jelas.</span></li><li><span><b>Kebijakan pengembalian tidak disebut</b>, dan itu mengkhawatirkan sebagian pengunjung.</span></li><li><span><b>Kode SKU menambah kekacauan</b> padahal tidak relevan bagi kebanyakan pengguna.</span></li></ol></div></div>'],
['Sesudah','<div class="cs2"><figure style="margin:0"><img class="cimg" src="images/ferplast-sesudah.jpg" alt="Halaman produk Ferplast sesudah perbaikan dengan lima perubahan bernomor"></figure><div><b style="font:800 28px Fraunces,serif">Lima perubahan</b><ol><li><span><b>Breadcrumb dipindah ke kiri</b> agar lebih rapi.</span></li><li><span><b>Bintang rating dinaikkan</b> ke bawah judul supaya lebih banyak yang melihat.</span></li><li><span><b>Tombol Shop Pay dihapus</b> untuk menyederhanakan jalur beli. Shop Pay tetap tersedia saat checkout.</span></li><li><span><b>Info cicilan, pengiriman, dan pengembalian</b> digabung dalam satu kotak yang lebih rapi.</span></li><li><span><b>Elemen pemikat</b> seperti logo PayPal diangkat lebih ke atas.</span></li></ol></div></div><div class="st s2"><div><b>+23%</b><span>penjualan selama pengujian</span></div><div><b>+42%</b><span>pendapatan per pengunjung</span></div></div><p style="margin-top:18px;max-width:70ch">Kaitan dengan IMK (interpretasi kami): jalur beli yang lebih jelas dan ada jalan kembali (user control and freedom), tampilan lebih bersih (aesthetic and minimalist design), dan informasi pengembalian yang terlihat (visibility dan kepercayaan).</p>']];
CT.forEach((t,i)=>{const b=document.createElement('button');b.setAttribute('role','tab');b.textContent=t[0];b.onclick=()=>cs(i);$('ctab').appendChild(b)});
function cs(k){[...$('ctab').children].forEach((b,i)=>b.setAttribute('aria-selected',i==k));$('cb').innerHTML=CT[k][1]}cs(0);
